<a href="https://colab.research.google.com/github/ttogle918/ds-section1-sprint3/blob/master/n131-vectors-and-matrices/n131a-vectors-matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src='https://i.imgur.com/RDAD11M.png' width = '200' align = 'right'>

## *DATA SCIENCE / SECTION 1 / SPRINT 3 / NOTE 1*

# 📝 Assignment

## 1. Portfolio

`Dot product` & `Matrix Multiplication` 을 이용하여 다음 포트폴리오의 사람별 총합을 계산하세요.
- 결과는 `res`에 list형태로 저장합니다.

|People|Name|Price|Amount|
|:-:|:-:|:-:|:-:|
|X|A|100|35|
|X|B|500|10|
|X|C|250|25|
|X|D|50|40|
|Y|A|100|-|
|Y|B|500|50|
|Y|C|250|50|
|Y|D|50|-|
|Z|A|100|-|
|Z|B|500|-|
|Z|C|250|100|
|Z|D|50|-|



pandas 이용

In [1]:
# 이곳에 답안을 작성하시기 바랍니다
import numpy as np
import pandas as pd

df = pd.DataFrame({'People' :['X', 'X', 'X', 'X', 'Y', 'Y', 'Y', 'Y', 'Z', 'Z', 'Z', 'Z'],
                   'Name' :['A', 'B', 'C', 'D', 'A', 'B', 'C', 'D', 'A', 'B', 'C', 'D'],
                   'Price' :[100, 500, 250, 50, 100, 500, 250, 50, 100, 500, 250, 50],
                   'Amount' : [35, 10, 25, 40, np.nan, 50, 50, np.nan, np.nan, np.nan, 100, np.nan]
                  })
df = df.fillna(0)
df['multiple'] = df['Price'] * df['Amount']
df

People Name  Price  Amount  multiple
0       X    A    100    35.0    3500.0
1       X    B    500    10.0    5000.0
2       X    C    250    25.0    6250.0
3       X    D     50    40.0    2000.0
4       Y    A    100     0.0       0.0
5       Y    B    500    50.0   25000.0
6       Y    C    250    50.0   12500.0
7       Y    D     50     0.0       0.0
8       Z    A    100     0.0       0.0
9       Z    B    500     0.0       0.0
10      Z    C    250   100.0   25000.0
11      Z    D     50     0.0       0.0

In [2]:
amount = df['multiple'].groupby(df['People'])

In [3]:
res = list(amount.sum())
res

[16750.0, 37500.0, 25000.0]

## 2. Norms

주어진 값 $x_0, x_1, ... x_n$ 를 element로 갖는 벡터 $v$에 대하여 

$L_1$ Norm 의 정의는 다음과 같습니다. 

$|v| = |x_0| + |x_1| + ... + |x_n|$

$L_2$ Norm 의 정의는 다음과 같습니다.

$||v|| = \sqrt {{x_0}^2 + {x_1}^2 + ... + {x_n}^2}$

이를 참조하여 주어진 벡터에 대해서 $L_2$ Norm 의 값과 $L_1$ Norm 의 값의 차이(**절대값**)를 계산하는 함수를 만드세요.



In [4]:
def L1Norm(v) :
  v = abs(v)
  return sum(v)

def L2Norm(v) :
  v = np.square(v)
  return np.sqrt(sum(v))

def NormDif(v): # v = np.array()
  return abs ( L1Norm(v) - L2Norm(v) )

In [5]:
NormDif(np.array([0, 1, 2, -2, -3]))

3.7573593128807152

## 3. Errors



- 2개의 벡터와, error의 타입을 입력받아 그 결과값을 계산하는 함수를 작성하세요.

- 여기서 error의 타입은 `MSE`, `MAE` 2가지 입니다.



MSE : Mean Squared Error (평균 제곱 오차)
*  오차의 제곱에 대한 평균을 취한 값
*  통계적 추정의 정확성에 대한 질적인 척도
*  회귀에서 자주 사용되는 손실 함수 
```
np.mean( np.square(y-pred) )
```
RMSE : 평균 제곱근 오차 ( MSE 앞에 sqrt 추가 )

MAE : Mean Absolute Error (평균 절대 오차)
*  AE : 절대 오차 ( 실제 값과 예측 값과의 차이 )
*  절대값을 구함
*  회귀지표로써 사용된다.
```
np.mean( np.abs(y-pred) )
```

In [6]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
# x : y_test
# y : y_pred
def error(x, y, type) :
  if type == 'MSE' :
    return np.mean( np.square(x - y) )
    # return mean_squared_error(x, y)
  elif type == 'MAE' :
    return np.mean( np.abs(x - y) )
    # return mean_absolute_error(x, y)
  return None

In [7]:
error(np.array([0, 1, 1, 2, 4]), np.array([1, 1, 2, 3, 2]), 'MSE')

1.4

In [8]:
error(np.array([0, 1, 1, 2, 4]), np.array([1, 1, 2, 3, 2]), 'MAE')

1.0

# 4. Inverse

- 주어진 matrix에 대해서 inverse matrix를 계산하여 반환하는 함수를 작성하세요. 
- 이 때 inverse 계산이 불가능 한 경우 `-1` 을 반환합니다.

In [9]:
def myInverse(m) : # m = np.array()
  if np.linalg.det(m) == 0 :
    return -1 # 'not exist inverse matrix'
  return np.linalg.inv(m)

In [10]:
print( np.array(range(4)).reshape(2,2))
print( myInverse(np.array(range(4)).reshape(2,2)) )
print( myInverse(np.array( [[0, 2], [2, 0]]) ))

[[0 1]
 [2 3]]
[[-1.5  0.5]
 [ 1.   0. ]]
[[0.  0.5]
 [0.5 0. ]]


# 🔥 도전과제 



다음 링크의 내용을 참조하여 **Cramer's rule**을 사용해 $x_1$, $x_2$, $x_3$의 값을 구하세요.

<https://youtu.be/6StS7VjtuGI>


$x_1$ + $2x_3$ = 6

$-3x_1$ + $4x_2$ + $6x_3$ = 30

$-x_1$ $-2x_2$ + $3x_3$ = 8



```
x1 = A
```

x1에 A를 대입했을 때(np.array 형식), 왜 A까지 바뀌는지? copy형식이 아니라 deep copy... 원본 주소값을 공유하는 같다.

```
x1 = A.copy()
```
이렇게 해야 shallow copy가 되어 값만 복사된다. ( 다른 메모리 공간에 상주해있다. )


In [30]:
A = np.array( [[1, 0, 2],
                [-3, 4, 6],
                [-1, -2, 3]] )

value = np.array([6, 30, 8])

det_A = np.linalg.det(A)

In [31]:
x1 = A.copy()
x1[:,0] = value
det_x1 = np.linalg.det(x1)

x1

array([[ 6,  0,  2],
       [30,  4,  6],
       [ 8, -2,  3]])

In [34]:
x2 = A.copy()
x2[:,1] = value
det_x2 = np.linalg.det(x2)
x2

array([[ 1,  6,  2],
       [-3, 30,  6],
       [-1,  8,  3]])

In [35]:
x3 = A.copy()
x3[:,2] = value
det_x3 = np.linalg.det(x3)
x3

array([[ 1,  0,  6],
       [-3,  4, 30],
       [-1, -2,  8]])

In [36]:
print('x1 :', det_x1 / det_A )
print('x2 :', det_x2 / det_A )
print('x3 :', det_x3 / det_A )

x1 : -0.9090909090909088
x2 : 1.6363636363636358
x3 : 3.4545454545454533
